### ISSUE TITLE
判断 commit-msg 中 是否包含 jira 号有问题

### ISSUE THREAD

**Issue by adispring** [adispring/git-client-hook#3]
当前情况是： 判断 commit-msg 中 是否包含 branchName。
改进：需要使用正则匹配，匹配出 branchName 中的 Jira 号，然后判断 commit-msg 中是否包含 Jira 号，而不是判断是否包含 branchName。

**Comment by csqian** [comment]
#6 
```shell
grep -oh '[A-Z][A-Z_0-9]\+-[0-9]\+'
```
